//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ACTION")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub actionid: i32,
    pub action: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::boxhistory::Entity")]
    Boxhistory,
    #[sea_orm(has_many = "super::itemhistory::Entity")]
    Itemhistory,
    #[sea_orm(has_many = "super::personhist::Entity")]
    Personhist,
}

impl Related<super::boxhistory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Boxhistory.def()
    }
}

impl Related<super::itemhistory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Itemhistory.def()
    }
}

impl Related<super::personhist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Personhist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
