//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "BOXHISTORY")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub boxhistory_id: i32,
    pub time: DateTimeWithTimeZone,
    pub barcode: String,
    pub itemid: Option<i32>,
    pub itemcount: Option<i32>,
    pub userid: i32,
    pub actionid: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::action::Entity",
        from = "Column::Actionid",
        to = "super::action::Column::Actionid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Action,
    #[sea_orm(
        belongs_to = "super::rvitem::Entity",
        from = "Column::Itemid",
        to = "super::rvitem::Column::Itemid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Rvitem,
    #[sea_orm(
        belongs_to = "super::rvperson::Entity",
        from = "Column::Userid",
        to = "super::rvperson::Column::Userid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Rvperson,
}

impl Related<super::action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Action.def()
    }
}

impl Related<super::rvitem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rvitem.def()
    }
}

impl Related<super::rvperson::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rvperson.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
