//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ITEMHISTORY")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub itemhistid: i32,
    pub time: DateTimeWithTimeZone,
    pub count: Option<i32>,
    pub actionid: i32,
    pub itemid: i32,
    pub userid: i32,
    pub priceid1: i32,
    pub priceid2: Option<i32>,
    pub saldhistid: Option<i32>,
    #[sea_orm(unique)]
    pub itemhistid2: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::action::Entity",
        from = "Column::Actionid",
        to = "super::action::Column::Actionid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Action,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Itemhistid2",
        to = "Column::Itemhistid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::price::Entity",
        from = "Column::Priceid1",
        to = "super::price::Column::Priceid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Price2,
    #[sea_orm(
        belongs_to = "super::price::Entity",
        from = "Column::Priceid2",
        to = "super::price::Column::Priceid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Price1,
    #[sea_orm(
        belongs_to = "super::rvitem::Entity",
        from = "Column::Itemid",
        to = "super::rvitem::Column::Itemid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Rvitem,
    #[sea_orm(
        belongs_to = "super::rvperson::Entity",
        from = "Column::Userid",
        to = "super::rvperson::Column::Userid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Rvperson,
    #[sea_orm(
        belongs_to = "super::saldohistory::Entity",
        from = "Column::Saldhistid",
        to = "super::saldohistory::Column::Saldhistid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Saldohistory,
}

impl Related<super::action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Action.def()
    }
}

impl Related<super::rvitem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rvitem.def()
    }
}

impl Related<super::rvperson::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rvperson.def()
    }
}

impl Related<super::saldohistory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Saldohistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
