//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod action;
pub mod boxhistory;
pub mod itemhistory;
pub mod personhist;
pub mod preferences;
pub mod price;
pub mod prodgroup;
pub mod role;
pub mod rvbox;
pub mod rvitem;
pub mod rvperson;
pub mod saldohistory;
pub mod temppassword;
