//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "PERSONHIST")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub pershistid: i32,
    pub time: DateTimeWithTimeZone,
    pub ipaddress: Option<String>,
    pub actionid: i32,
    pub userid1: i32,
    pub userid2: i32,
    pub saldhistid: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::action::Entity",
        from = "Column::Actionid",
        to = "super::action::Column::Actionid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Action,
    #[sea_orm(
        belongs_to = "super::rvperson::Entity",
        from = "Column::Userid1",
        to = "super::rvperson::Column::Userid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Rvperson2,
    #[sea_orm(
        belongs_to = "super::rvperson::Entity",
        from = "Column::Userid2",
        to = "super::rvperson::Column::Userid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Rvperson1,
    #[sea_orm(
        belongs_to = "super::saldohistory::Entity",
        from = "Column::Saldhistid",
        to = "super::saldohistory::Column::Saldhistid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Saldohistory,
}

impl Related<super::action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Action.def()
    }
}

impl Related<super::saldohistory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Saldohistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
