//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::action::Entity as Action;
pub use super::boxhistory::Entity as Boxhistory;
pub use super::itemhistory::Entity as Itemhistory;
pub use super::knex_migrations::Entity as KnexMigrations;
pub use super::knex_migrations_lock::Entity as KnexMigrationsLock;
pub use super::personhist::Entity as Personhist;
pub use super::preferences::Entity as Preferences;
pub use super::price::Entity as Price;
pub use super::prodgroup::Entity as Prodgroup;
pub use super::role::Entity as Role;
pub use super::rvbox::Entity as Rvbox;
pub use super::rvitem::Entity as Rvitem;
pub use super::rvperson::Entity as Rvperson;
pub use super::saldohistory::Entity as Saldohistory;
pub use super::temppassword::Entity as Temppassword;
