//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "PRICE")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub priceid: i32,
    pub barcode: String,
    pub count: i32,
    pub buyprice: i32,
    pub sellprice: i32,
    pub itemid: i32,
    pub userid: i32,
    pub starttime: Option<DateTimeWithTimeZone>,
    pub endtime: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::rvitem::Entity",
        from = "Column::Itemid",
        to = "super::rvitem::Column::Itemid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Rvitem,
    #[sea_orm(
        belongs_to = "super::rvperson::Entity",
        from = "Column::Userid",
        to = "super::rvperson::Column::Userid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Rvperson,
}

impl Related<super::rvitem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rvitem.def()
    }
}

impl Related<super::rvperson::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rvperson.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
