//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ROLE")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub roleid: i32,
    pub role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::rvperson::Entity")]
    Rvperson,
}

impl Related<super::rvperson::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rvperson.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
