//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "RVPERSON")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub userid: i32,
    pub createdate: DateTimeWithTimeZone,
    pub roleid: i32,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(unique)]
    pub univident: String,
    pub pass: String,
    pub saldo: i32,
    pub realname: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub rfid: Option<String>,
    pub privacy_level: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::boxhistory::Entity")]
    Boxhistory,
    #[sea_orm(has_many = "super::itemhistory::Entity")]
    Itemhistory,
    #[sea_orm(has_many = "super::price::Entity")]
    Price,
    #[sea_orm(
        belongs_to = "super::role::Entity",
        from = "Column::Roleid",
        to = "super::role::Column::Roleid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Role,
    #[sea_orm(has_many = "super::saldohistory::Entity")]
    Saldohistory,
    #[sea_orm(has_one = "super::temppassword::Entity")]
    Temppassword,
}

impl Related<super::boxhistory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Boxhistory.def()
    }
}

impl Related<super::itemhistory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Itemhistory.def()
    }
}

impl Related<super::price::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Price.def()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Role.def()
    }
}

impl Related<super::saldohistory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Saldohistory.def()
    }
}

impl Related<super::temppassword::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Temppassword.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
