//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "SALDOHISTORY")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub saldhistid: i32,
    pub userid: i32,
    pub time: DateTimeWithTimeZone,
    pub saldo: Option<i32>,
    pub difference: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::itemhistory::Entity")]
    Itemhistory,
    #[sea_orm(has_many = "super::personhist::Entity")]
    Personhist,
    #[sea_orm(
        belongs_to = "super::rvperson::Entity",
        from = "Column::Userid",
        to = "super::rvperson::Column::Userid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Rvperson,
}

impl Related<super::itemhistory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Itemhistory.def()
    }
}

impl Related<super::personhist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Personhist.def()
    }
}

impl Related<super::rvperson::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rvperson.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
